version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: faculty_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hellotome@99
      POSTGRES_DB: faculty_leave
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: faculty_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: faculty_backend
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: faculty_leave
      REDIS_HOST: redis
      REDIS_PORT: 6379

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: faculty_worker
    command: node src/queues/reportQueue.js
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: faculty_leave
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  postgres_data:
  redis_data:
